### ISSUE TITLE
Error while trying to generate a new token ::  'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by XaviTorello** [nicolaiarocci/flask-sentinel#16]
There was an error while trying to generate a new token

```
$ curl -k -X POST -d "client_id=$TOKEN&grant_type=password&username=$USER&password=$PASS" https://$HOST:$PORT/oauth/token

...
...
...

Traceback (most recent call last):
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask_oauthlib/provider/oauth2.py", line 507, in decorated
    uri, http_method, body, headers, credentials
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 111, in create_token_response
    request, self.default_token_type)
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 112, in create_token_response
    self.validate_token_request(request)
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 187, in validate_token_request
    request.password, request.client, request):
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask_oauthlib/provider/oauth2.py", line 944, in validate_user
    username, password, client, request, *args, **kwargs
  File "/Users/k/.virtualenvs/oKW-apipub3/lib/python3.5/site-packages/flask_sentinel/data.py", line 108, in get_user
    user_hash = user['hashpw'].encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
```

Version and installed packages on this virtualenv
```
$ python -V
Python 3.5.2

$ pip list
bcrypt (3.1.1)
Cerberus (0.9.2)
cffi (1.8.3)
cryptography (1.5.2)
Eve (0.6.4)
Events (0.2.1)
Flask (0.10.1)
Flask-OAuthlib (0.9.3)
Flask-PyMongo (0.4.1)
Flask-Sentinel (0.0.5)
idna (2.1)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
oauthlib (2.0.0)
pip (8.1.2)
pyasn1 (0.1.9)
pycparser (2.14)
pymongo (3.3.0)
pyOpenSSL (16.1.0)
redis (2.10.5)
requests (2.11.1)
requests-oauthlib (0.7.0)
setuptools (28.3.0)
simplejson (3.8.2)
six (1.10.0)
Werkzeug (0.11.3)
wheel (0.30.0a0)
```

**Comment by XaviTorello** [comment]
Workaround for py3, avoid encoding to utf-8

flask_sentinel/data.py:#108
```
user_hash = user['hashpw'].encode('utf-8')

to

user_hash = user['hashpw']
```

**Comment by XaviTorello** [comment]
Reviewing the code of the repo, I see that it was managed to troubleshoot this issue

But it seems that the latest changes applied on 0.0.6 version has not been uploaded to pip.

I'm going to close this issue and open a new one
