### ISSUE TITLE
Error when load sentinel on Python 3.4

### ISSUE THREAD

**Issue by ddurieux** [nicolaiarocci/flask-sentinel#6]
When try to load sentinel in python3.4, I have the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/site-packages/flask_sentinel/__init__.py", line 1, in <module>
    from flask_sentinel import ResourceOwnerPasswordCredentials, oauth  # noqa
ImportError: cannot import name 'ResourceOwnerPasswordCredentials'
```

**Comment by nicolaiarocci** [comment]
Hello, that should be fixed on the development branch (see https://github.com/nicolaiarocci/flask-sentinel/commit/a90b7377242672701b8160ba826f111bba18714b). Could you please try again with v0.4-dev and see if it's solved for you? Thanks!
